package rh.ptp.quizapp.model;

public enum QuizCategory {
    DAILY_QUIZ("Tägliches Quiz"),
    GENERAL_KNOWLEDGE("Allgemeinwissen"),
    SCIENCE("Wissenschaft"),
    HISTORY("Geschichte"),
    GEOGRAPHY("Geographie"),
    ENTERTAINMENT("Unterhaltung"),
    ART_AND_LITERATURE("Kunst und Literatur"),
    SPORTS("Sport"),
    MUSIC("Musik"),
    FILM_AND_TELEVISION("Film und Fernsehen"),
    TECHNOLOGY("Technologie"),
    MYTHOLOGY("Mythologie"),
    PHILOSOPHY("Philosophie"),
    RELIGIOUS_STUDIES("Religionswissenschaft"),
    PSYCHOLOGY("Psychologie"),
    SOCIOLOGY("Soziologie"),
    ANTHROPOLOGY("Anthropologie"),
    POLITICS("Politik"),
    ECONOMICS("Wirtschaft"),
    FINANCE("Finanzwesen"),
    LAW("Rechtswissenschaft"),
    MATHEMATICS("Mathematik"),
    COMPUTER_SCIENCE("Informatik"),
    ROBOTICS("Robotik"),
    ARTIFICIAL_INTELLIGENCE("Künstliche Intelligenz"),
    PROGRAMMING("Programmierung"),
    LOGIC("Logik"),
    LINGUISTICS("Sprachwissenschaften"),
    ENGLISH("Englisch"),
    FRENCH("Französisch"),
    SPANISH("Spanisch"),
    GERMAN("Deutsch"),
    LATIN("Latein"),
    ANCIENT_GREEK("Altgriechisch"),
    ARABIC("Arabisch"),
    CHINESE("Chinesisch"),
    JAPANESE("Japanisch"),
    CULTURAL_STUDIES("Kulturwissenschaft"),
    COUNTRY_STUDIES("Landeskunde"),
    TRAVEL("Reisen"),
    TOURISM("Tourismus"),
    ARCHITECTURE("Architektur"),
    DESIGN("Design"),
    FASHION("Mode"),
    PHOTOGRAPHY("Fotografie"),
    FILM_HISTORY("Filmgeschichte"),
    COMICS_AND_MANGA("Comic und Manga"),
    ANIME("Anime"),
    THEATRE("Theater"),
    OPERA("Oper"),
    CLASSIC_LITERATURE("Klassische Literatur"),
    MODERN_LITERATURE("Moderne Literatur"),
    POETRY("Poesie"),
    MUSIC_THEORY("Musiktheorie"),
    COMPOSERS("Komponisten"),
    INSTRUMENTS("Instrumentenkunde"),
    JAZZ("Jazz"),
    ROCK("Rockmusik"),
    POP("Popmusik"),
    HIP_HOP("Hip-Hop"),
    ELECTRONIC_MUSIC("Elektronische Musik"),
    SPORTS_TYPES("Sportarten"),
    SOCCER("Fußball"),
    TENNIS("Tennis"),
    GOLF("Golf"),
    ATHLETICS("Leichtathletik"),
    SWIMMING("Schwimmen"),
    WINTER_SPORTS("Wintersport"),
    MOTOR_SPORTS("Motorsport"),
    ESPORTS("eSports"),
    VIDEO_GAMES("Videospiele"),
    BOARD_GAMES("Brettspiele"),
    CARD_GAMES("Kartenspiele"),
    MAGIC("Zauberei"),
    ILLUSION("Illusion"),
    HISTORY_OF_TECHNOLOGY("Technikgeschichte"),
    NATURAL_SCIENCES("Naturwissenschaften"),
    BIOLOGY("Biologie"),
    CHEMISTRY("Chemie"),
    PHYSICS("Physik"),
    ASTRONOMY("Astronomie"),
    GEOLOGY("Geologie"),
    METEOROLOGY("Meteorologie"),
    CLIMATE_CHANGE("Klimawandel"),
    ECOLOGY("Ökologie"),
    ENVIRONMENTAL_PROTECTION("Umweltschutz"),
    MEDICINE("Medizin"),
    HEALTH("Gesundheit"),
    NUTRITION("Ernährung"),
    FITNESS("Fitness"),
    YOGA("Yoga"),
    MEDITATION("Meditation"),
    PARENTING("Erziehung"),
    EDUCATION("Bildung"),
    PEDAGOGY("Pädagogik"),
    FOLKLORE("Volkskunde"),
    ARCHAEOLOGY("Archäologie"),
    PALEONTOLOGY("Paläontologie"),
    OCEANOGRAPHY("Ozeanografie"),
    SPACE_EXPLORATION("Raumfahrt"),
    GASTRONOMY("Gastronomie");
    private final String displayName;

    QuizCategory(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
