name: Build & Push Frontend Image

on:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Variables (BRANCH, SHA, TAG)
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | sed 's/\//-/g')
          SHA=$(git rev-parse --short HEAD)
          if [ "$BRANCH" = "main" ]; then
            TAG=latest
          elif [ "$BRANCH" = "hosting" ]; then
            TAG=stable
          elif [ "$BRANCH" = "dev" ]; then
            TAG=beta
          else
            TAG=dev-${BRANCH}-${SHA}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  docker-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: |
          docker build --build-arg REACT_APP_MAIL=${{ secrets.MAIL_ANSWER_TO }} \
            --build-arg REACT_APP_API_URL=${{ vars.SERVER_URL }}:9090/api \
            -t lesommer2019/trivify-frontend:${{ steps.vars.outputs.tag }} ./frontend

  docker-push:
    needs: [setup, docker-build]
    runs-on: ubuntu-latest
    steps:
      - name: Push Frontend
        run: docker push lesommer2019/trivify-frontend:${{ steps.vars.outputs.tag }}